# brew tap-new uses this file to generate a bottle publish workflow for the new tap
name: brew pr-pull

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      head_sha:
        description: Expected pull request head commit SHA (optional)
      pull_request_already_merged:
        description: Skip cherry-picking because the pull request is already merged
        required: true
        type: boolean
        default: false

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  pr-pull:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@c8707045ccae42888fe98e86f2ee8938bc7cc193 # 2026.08.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@c8707045ccae42888fe98e86f2ee8938bc7cc193 # 2026.08.10.1

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          HEAD_SHA: ${{ inputs.head_sha }}
          NO_CHERRY_PICK: ${{ inputs.pull_request_already_merged }}
          PULL_REQUEST: ${{ inputs.pull_request }}
        run: |
          args=(--debug --tap="$GITHUB_REPOSITORY")
          if [[ "$NO_CHERRY_PICK" == "true" ]]
          then
            args+=(--no-cherry-pick)
          fi

          if [[ -n "$HEAD_SHA" ]]
          then
            args+=(--head-sha="$HEAD_SHA")
          fi

          brew pr-pull "${args[@]}" "$PULL_REQUEST"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@c8707045ccae42888fe98e86f2ee8938bc7cc193 # 2026.08.10.1
        with:
          branch: main
